name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 00 4 * * *

jobs:
  alpine:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
          - edge
          - 3.20.3
          - 3.20
          - 3.19.4
          - 3.19
          - 3.18.9
          - 3.18
          - 3.17.10
          - 3.17
    name: Alpine
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:alpine"
          push: true
          tags: ghcr.io/${{ github.repository }}/alpine:${{ matrix.tag }}
          build-args:
            TAG: ${{ matrix.tag }}

      - name: Build container image
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:alpine"
          push: true
          tags: ghcr.io/${{ github.repository }}/alpine:${{ github.head_ref }}-${{ matrix.tag }}
          build-args:
            TAG: ${{ matrix.tag }}
